### PR TITLE
Add a custom function to generate tag id

### PR DESCRIPTION
**Pull request by niklashempel**
This PR solves #88

### CODE REVIEW

**Review by JaleelB — APPROVED** [review]
Nice! LGTM

**Comment by niklashempel** [comment]
Done. I also updated the snippet in tag-input.mdx

**Review by JaleelB — APPROVED** [review]
LGTM

**Comment by juliusmarminge** [comment]
Hey @JaleelB  - can you push a new release so this can be used?

**Comment by JaleelB** [comment]
> Hey @JaleelB - can you push a new release so this can be used?

Will do @juliusmarminge

**Pull request merged**
